#!/usr/bin/env bash
# installing and confuring HAproxy to serve as load balancer
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.4 -y
sudo apt-get -y update
sudo apt-get -y install haproxy=2.4.\*
echo -e '
frontend http-in
\tmode http
\tbind *:80
\tdefault_backend web_servers

backend web_servers
\tbalance roundrobin
\tserver 5696-web-01 3.92.84.54:80 check
\tserver 5696-web-02 54.84.251.2:80 check
' >> /etc/haproxy/haproxy.cfg
echo -e '
ENABLED=1' >> /etc/default/haproxy
service haproxy restart
