#!/usr/bin/env bash
# Debugs error where sites-available/default is unlinked to site-enabled default
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
sudo service nginx restart
sudo pkill -o nginx
