#!/usr/bin/env bash
# configuring nginx server for /redirect_me to redirect to another page
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
sed -i '/^\tserver_name.*/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
service nginx restart

